#!/bin/bash

mkdir -pv $LFS/{dev,proc,sys,run}

mount -v --bind /dev $LFS/dev

mount -v --bind /dev/pts $LFS/dev/pts
mount -vt proc proc $LFS/proc
mount -vt sysfs sysfs $LFS/sys
mount -vt tmpfs tmpfs $LFS/run

if [ -h $LFS/dev/shm ]; then
  (cd $LFS/dev; mkdir $(readlink shm))
else
  mount -vt tmpfs -o nosuid,nodev tmpfs $LFS/dev/shm
fi

