#!/bin/bash

# This block must be edited to suit your needs.
chroot "$LFS" /usr/bin/env -i   \
    HOME=/root                  \
    TERM="$TERM"                \
    PS1='(lfs chroot) \u:\w\$ ' \
    PATH=/usr/bin:/usr/sbin     \
    MAKEFLAGS="-j**EDITME$(nproc)EDITME**"      \
    TESTSUITEFLAGS="-j**EDITME$(nproc)EDITME**" \
    /bin/bash --login
# End of editable block.

