#!/bin/bash

# This block must be edited to suit your needs.
grep -l '**EDITMElibfooEDITME**.*deleted' /proc/*/maps | tr -cd 0-9\\n | xargs -r ps u
# End of editable block.

./configure --prefix=/usr/pkg/libfoo/1.1
make
make install

./configure --prefix=/usr
make
make DESTDIR=/usr/pkg/libfoo/1.1 install

