#!/bin/bash

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/xz-5.6.0

make

make check

make install

make distclean

CC="gcc -m64" ./configure \
    --host=x86_64-pc-linux-gnu      \
    --prefix=/usr                 \
    --libdir=/usr/lib64           \
    --disable-static

make

make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib64/* /usr/lib64
rm -rf DESTDIR

