#!/bin/bash

make BUILD_STATIC=no

make -j1 check

make BUILD_STATIC=no PREFIX=/usr install

make clean

CC="gcc -m32" make BUILD_STATIC=no

make BUILD_STATIC=no PREFIX=/usr LIBDIR=/usr/lib32 DESTDIR=$(pwd)/m32 install &&
cp -a m32/usr/lib32/* /usr/lib32/


