#!/bin/bash

ABI=32 ./configure ...

cp -v config{fsf,}.guess
cp -v config{fsf,}.sub
ABI=x32 ./configure --prefix=/usr    \
            --enable-cxx     \
            --disable-static \
            --docdir=/usr/share/doc/gmp-6.3.0

make
make html

make check 2>&1 | tee gmp-check-log

awk '/# PASS:/{total+=$3} ; END{print total}' gmp-check-log

make install
make install-html

make distclean

cp -v configfsf.guess config.guess
cp -v configfsf.sub   config.sub

ABI="64" \
CFLAGS="-m64 -O2 -pedantic -fomit-frame-pointer $CFLAGS" \
CXXFLAGS="$CFLAGS" \
PKG_CONFIG_PATH="/usr/lib64/pkgconfig" \
./configure                      \
    --host=x86_64-pc-linux-gnu     \
    --prefix=/usr                \
    --disable-static             \
    --enable-cxx                 \
    --libdir=/usr/lib64          \
    --includedir=/usr/include/m64/gmp

sed -i 's/$(exec_prefix)\/include/$\(includedir\)/' Makefile
make

make check 2>&1 | tee gmp-check-log

awk '/# PASS:/{total+=$3} ; END{print total}' gmp-check-log

make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib64/* /usr/lib64
cp -Rv DESTDIR/usr/include/m64/* /usr/include/m64/
rm -rf DESTDIR

