#!/bin/bash

sed -i 's/str\(cmp.*package\)/strn\1, strlen(pkg->why)/' cli/main.c

./configure --prefix=/usr              \
            --disable-static           \
            --docdir=/usr/share/doc/pkgconf-2.0.3

make

make install

ln -sv pkgconf   /usr/bin/pkg-config
ln -sv pkgconf.1 /usr/share/man/man1/pkg-config.1

