#!/bin/bash

./configure --prefix=/usr         \
            --disable-static      \
            --docdir=/usr/share/doc/acl-2.3.2

make

make install

make distclean

CC="gcc -m64" ./configure \
    --prefix=/usr         \
    --disable-static      \
    --libdir=/usr/lib64   \
    --libexecdir=/usr/lib64   \
    --host=x86_64-pc-linux-gnu

make

make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib64/* /usr/lib64
rm -rf DESTDIR

