#!/bin/bash

./configure --prefix=/usr           \
            --mandir=/usr/share/man \
            --with-shared           \
            --without-debug         \
            --without-normal        \
            --with-cxx-shared       \
            --enable-pc-files       \
            --enable-widec          \
            --with-pkg-config-libdir=/usr/lib/pkgconfig

make

make DESTDIR=$PWD/dest install
install -vm755 dest/usr/lib/libncursesw.so.6.4 /usr/lib
rm -v  dest/usr/lib/libncursesw.so.6.4
sed -e 's/^#if.*XOPEN.*$/#if 1/' \
    -i dest/usr/include/curses.h
cp -av dest/* /

for lib in ncurses form panel menu ; do
    ln -sfv lib${lib}w.so /usr/lib/lib${lib}.so
    ln -sfv ${lib}w.pc    /usr/lib/pkgconfig/${lib}.pc
done

ln -sfv libncursesw.so /usr/lib/libcurses.so

cp -v -R doc -T /usr/share/doc/ncurses-6.4-20230520

make distclean
./configure --prefix=/usr     \
            --with-shared     \
            --without-normal  \
            --with-cxx-shared \
            --without-debug   \
            --without-cxx-binding \
            --with-abi-version=5
make sources libs
cp -av lib/lib*.so.5* /usr/lib

make distclean

CC="gcc -m64" CXX="g++ -m64" \
./configure --prefix=/usr           \
            --host=x86_64-pc-linux-gnu \
            --libdir=/usr/lib64     \
            --mandir=/usr/share/man \
            --with-shared           \
            --without-debug         \
            --without-normal        \
            --with-cxx-shared       \
            --enable-pc-files       \
            --enable-widec          \
            --with-pkg-config-libdir=/usr/lib64/pkgconfig

make

make DESTDIR=$PWD/DESTDIR install
mkdir -p DESTDIR/usr/lib64/pkgconfig
for lib in ncurses form panel menu ; do
    rm -vf                    DESTDIR/usr/lib64/lib${lib}.so
    echo "INPUT(-l${lib}w)" > DESTDIR/usr/lib64/lib${lib}.so
    ln -svf ${lib}w.pc        DESTDIR/usr/lib64/pkgconfig/$lib.pc
done
rm -vf                     DESTDIR/usr/lib64/libcursesw.so
echo "INPUT(-lncursesw)" > DESTDIR/usr/lib64/libcursesw.so
ln -sfv libncurses.so      DESTDIR/usr/lib64/libcurses.so
cp -Rv DESTDIR/usr/lib64/* /usr/lib64
rm -rf DESTDIR

