#!/bin/bash

sed -e '/^structured/s/xmlError \*/typeof(xmlCtxtGetLastError(NULL)) /' \
    -i gettext-tools/src/its.c

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/gettext-0.23

make

make check

make install
chmod -v 0755 /usr/lib/preloadable_libintl.so

