#!/bin/bash

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/expat-2.6.1

make

make check

make install

install -v -m644 doc/*.{html,css} /usr/share/doc/expat-2.6.1

sed -e "/^am__append_1/ s/doc//" -i Makefile
make clean

CC="gcc -m64" ./configure \
    --prefix=/usr        \
    --disable-static     \
    --libdir=/usr/lib64  \
    --host=x86_64-pc-linux-gnu

make

make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib64/* /usr/lib64
rm -rf DESTDIR

