#!/bin/bash

./configure --prefix=/usr          \
            --sysconfdir=/etc      \
            --with-openssl         \
            --with-xz              \
            --with-zstd            \
            --with-zlib

make

make install

for target in depmod insmod modinfo modprobe rmmod; do
  ln -sfv ../bin/kmod /usr/sbin/$target
done

ln -sfv kmod /usr/bin/lsmod

sed -e "s/^CLEANFILES =.*/CLEANFILES =/" -i man/Makefile
make clean

CC="gcc -m64" ./configure \
    --host=x86_64-pc-linux-gnu      \
    --prefix=/usr                 \
    --libdir=/usr/lib64           \
    --sysconfdir=/etc             \
    --with-openssl                \
    --with-xz                     \
    --with-zstd                   \
    --with-zlib                   \
    --with-rootlibdir=/usr/lib64

make

make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib64/* /usr/lib64
rm -rf DESTDIR

