#!/bin/bash

sed -e 's/GROUP="render"/GROUP="video"/' \
    -e 's/GROUP="sgx", //'               \
    -i rules.d/50-udev-default.rules.in

mkdir -p build
cd       build

meson setup ..                \
      --prefix=/usr           \
      --buildtype=release     \
      -D default-dnssec=no    \
      -D firstboot=false      \
      -D install-tests=false  \
      -D ldconfig=false       \
      -D sysusers=false       \
      -D rpmmacrosdir=no      \
      -D homed=disabled       \
      -D userdb=false         \
      -D man=disabled         \
      -D mode=release         \
      -D pamconfdir=no        \
      -D dev-kvm-mode=0660    \
      -D nobody-group=nogroup \
      -D sysupdate=disabled   \
      -D ukify=disabled       \
      -D docdir=/usr/share/doc/systemd-257

ninja

echo 'NAME="Linux From Scratch"' > /etc/os-release
ninja test

ninja install

tar -xf ../../systemd-man-pages-257.tar.xz \
    --no-same-owner --strip-components=1   \
    -C /usr/share/man

systemd-machine-id-setup

systemctl preset-all

rm -rf *

PKG_CONFIG_PATH="/usr/lib32/pkgconfig" \
CC="gcc -m32"                        \
CXX="g++ -m32"                       \
LANG=en_US.UTF-8                     \
meson setup ..                       \
      --prefix=/usr                  \
      --libdir=/usr/lib32            \
      --buildtype=release            \
      -D default-dnssec=no           \
      -D firstboot=false             \
      -D install-tests=false         \
      -D ldconfig=false              \
      -D sysusers=false              \
      -D rpmmacrosdir=no             \
      -D homed=disabled              \
      -D userdb=false                \
      -D man=disabled                \
      -D mode=release 

LANG=en_US.UTF-8 ninja

LANG=en_US.UTF-8 DESTDIR=$PWD/DESTDIR ninja install
cp -v DESTDIR/usr/lib32/libsystemd.so* /usr/lib32/
cp -v DESTDIR/usr/lib32/libudev.so* /usr/lib32/
cp -v DESTDIR/usr/lib32/pkgconfig/* /usr/lib32/pkgconfig/
rm -rf DESTDIR

