#!/bin/bash

sed -i '/test_mkfds/s/^/#/' tests/helpers/Makemodule.am

./configure --bindir=/usr/bin    \
            --libdir=/usr/lib    \
            --runstatedir=/run   \
            --sbindir=/usr/sbin  \
            --disable-chfn-chsh  \
            --disable-login      \
            --disable-nologin    \
            --disable-su         \
            --disable-setpriv    \
            --disable-runuser    \
            --disable-pylibmount \
            --disable-static     \
            --without-python     \
            ADJTIME_PATH=/var/lib/hwclock/adjtime \
            --docdir=/usr/share/doc/util-linux-2.39.3

make

bash tests/run.sh --srcdir=$PWD --builddir=$PWD

chown -R tester .
su tester -c "make -k check"

make install

make distclean

mv /usr/bin/ncursesw6-config{,.tmp}

CC="gcc -m64" \
./configure ADJTIME_PATH=/var/lib/hwclock/adjtime   \
            --host=x86_64-pc-linux-gnu \
            --libdir=/usr/lib64      \
            --docdir=/usr/share/doc/util-linux-2.39.3 \
            --disable-chfn-chsh      \
            --disable-login          \
            --disable-nologin        \
            --disable-su             \
            --disable-setpriv        \
            --disable-runuser        \
            --disable-pylibmount     \
            --disable-static         \
            --without-python

mv /usr/bin/ncursesw6-config{.tmp,}

make

make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib64/* /usr/lib64
rm -rf DESTDIR

