#!/bin/bash

./configure --prefix=/usr                           \
            --docdir=/usr/share/doc/procps-ng-4.0.5 \
            --disable-static                        \
            --disable-kill                          \
            --with-systemd

make

chown -R tester .
su tester -c "PATH=$PATH make check"

make install

