#!/bin/bash
set -e

cd $PKGDIR
./configure --prefix=/usr 		--sbindir=/usr/sbin 		--sysconfdir=/etc 		--libdir=/usr/lib 		--enable-securedir=/usr/lib/security 		--docdir=/usr/share/doc/linux-pam-1.6.1

make
make install
chmod -v 4755 /usr/sbin/unix_chkpwd
find /usr ! -type d -name "*.la" -exec rm -f -- "{}" +
exit
