#!/bin/bash
set -e

cd $PKGDIR
sed '20,$ d' -i trust/trust-extract-compat
cat >> trust/trust-extract-compat << "EOF"
# Copy existing anchor modifications to /etc/ssl/local
/usr/libexec/make-ca/copy-trust-modifications

# Update trust stores
/usr/sbin/make-ca -r
EOF

mkdir p11-build
cd p11-build

meson setup .. \
	--prefix=/usr \
	--libdir=/usr/lib \
	--buildtype=release \
	-Dtrust_paths=/etc/tls/trust-source:/tmp/p11kit_trust
ninja
ninja install
ln -sfv pkcs11/p11-kit-trust.so /usr/lib/libnssckbi.so
find /usr ! -type d -name "*.la" -exec rm -f -- "{}" +
exit
