#!/bin/bash
set -e

cd $PKGDIR
install -vdm755 /etc/ssl/local
/usr/sbin/make-ca -g
ln -sfv ../tls/certs/ca-bundle.crt /etc/ssl/cert.pem

mkdir -pv /etc/profile.d
cat > /etc/profile.d/pythoncerts.sh << "EOF"
# Begin /etc/profile.d/pythoncerts.sh

export _PIP_STANDALONE_CERT=/etc/tls/certs/ca-bundle.crt

# End /etc/profile.d/pythoncerts.sh
EOF
find /usr ! -type d -name "*.la" -exec rm -f -- "{}" +
exit
