#!/bin/bash
set -e

cd $PKGDIR
./configure --prefix=/usr \
		--sysconfdir=/etc \
		--disable-static \
		--with-ssl=openssl

make
make install
find /usr ! -type d -name "*.la" -exec rm -f -- "{}" +
exit
