#!/bin/bash
set -e

cd $PKGDIR
./configure --prefix=/usr             --disable-static             --with-openssl             --enable-threaded-resolver             --with-ca-path=/etc/ssl/certs             --without-libpsl
make
make install

rm -rf docs/examples/.deps
find docs \( -name Makefile\* -o               -name \*.1       -o               -name \*.3       -o               -name CMakeLists.txt \) -delete
cp -v -R docs -T /usr/share/doc/curl-8.8.0
find /usr ! -type d -name "*.la" -exec rm -f -- "{}" +
exit
