#!/bin/bash
set -e

cd $PKGDIR
./configure --prefix=/usr 		--sysconfdir=/etc 		--enable-utf8 		--enable-color 		--enable-nanorc 		--docdir=/usr/share/doc/nano-8.1
make
make install
install -vm644 doc/sample.nanorc /etc/nanorc
cat <<"EOF">>/etc/nanorc
bind ^Q exit all
bind ^Z undo main
bind ^Y redo main

set tabsize 4
#set tabstospaces

include "/usr/share/nano/*.nanorc"
EOF
find /usr ! -type d -name "*.la" -exec rm -f -- "{}" +
exit
