#!/bin/bash
set +h
set -e



PREV_SEC=${SECONDS}
      
ROOT=/

SCRIPT_ROOT=jhalfs

SRC_DIR=${ROOT}sources

VERSION=10.47
PKG_DEST=${SRC_DIR}/811-pcre2

PACKAGE=pcre2-10.47.tar.bz2
cd $SRC_DIR
PKGDIR=$(tar -tf $PACKAGE | head -n1 | sed 's@^./@@;s@/.*@@')
export PKGDIR VERSION PKG_DEST

if [ -d "$PKGDIR" ]; then rm -rf $PKGDIR; fi
if [ -d "$PKG_DEST" ]; then rm -rf $PKG_DEST; fi
if [ -d "${PKGDIR%-*}-build" ]; then  rm -rf ${PKGDIR%-*}-build; fi

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"


tar -xf $PACKAGE
cd $PKGDIR

export MAKEFLAGS="-j4"
SECONDS=${PREV_SEC}

# Start of LFS book script
./configure --prefix=/usr                       \
            --docdir=/usr/share/doc/pcre2-10.47 \
            --enable-unicode                    \
            --enable-jit                        \
            --enable-pcre2-16                   \
            --enable-pcre2-32                   \
            --enable-pcre2grep-libz             \
            --enable-pcre2grep-libbz2           \
            --enable-pcre2test-libreadline      \
            --disable-static
make
# make -k check >> $TEST_LOG 2>&1 || true
make -j1 install
make distclean
CC="gcc -m32" CXX="g++ -m32"               \
./configure --prefix=/usr                  \
            --libdir=/usr/lib32            \
            --host=i686-pc-linux-gnu       \
            --enable-unicode               \
            --enable-jit                   \
            --enable-pcre2-16              \
            --enable-pcre2-32              \
            --enable-pcre2grep-libz        \
            --enable-pcre2grep-libbz2      \
            --enable-pcre2test-libreadline \
            --disable-static
make
make -j1 DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /usr/lib32
rm -rf DESTDIR
echo -e "\n\nTotalseconds: $SECONDS\n"

# End of LFS book script

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"
cd $SRC_DIR
rm -rf $PKGDIR
if [ -d "${PKGDIR%-*}-build" ]; then  rm -rf ${PKGDIR%-*}-build; fi
exit
