#!/bin/bash
set +h
set -e



PREV_SEC=${SECONDS}
      
ROOT=/

SCRIPT_ROOT=jhalfs

SRC_DIR=${ROOT}sources

VERSION="260.1"
PKG_DEST=${SRC_DIR}/870-systemd

PACKAGE=systemd-260.1.tar.gz
cd $SRC_DIR
PKGDIR=$(tar -tf $PACKAGE | head -n1 | sed 's@^./@@;s@/.*@@')
export PKGDIR VERSION PKG_DEST

if [ -d "$PKGDIR" ]; then rm -rf $PKGDIR; fi
if [ -d "$PKG_DEST" ]; then rm -rf $PKG_DEST; fi
if [ -d "${PKGDIR%-*}-build" ]; then  rm -rf ${PKGDIR%-*}-build; fi

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"


tar -xf $PACKAGE
cd $PKGDIR

export MAKEFLAGS="-j4"
SECONDS=${PREV_SEC}

# Start of LFS book script
sed -e 's/GROUP="render"/GROUP="video"/' \
    -e 's/GROUP="sgx", //'               \
    -i rules.d/50-udev-default.rules.in
mkdir -p build
cd       build

meson setup ..                \
      --prefix=/usr           \
      --buildtype=release     \
      -D default-dnssec=no    \
      -D firstboot=false      \
      -D install-tests=false  \
      -D ldconfig=false       \
      -D sysusers=false       \
      -D rpmmacrosdir=no      \
      -D homed=disabled       \
      -D man=disabled         \
      -D mode=release         \
      -D pamconfdir=no        \
      -D dev-kvm-mode=0660    \
      -D nobody-group=nogroup \
      -D sysupdate=disabled   \
      -D ukify=disabled       \
      -D docdir=/usr/share/doc/systemd-260.1
ninja
ninja install
tar -xf ../../systemd-man-pages-260.1.tar.xz \
    --no-same-owner --strip-components=1     \
    -C /usr/share/man
# echo 'NAME="Linux From Scratch"' > /etc/os-release >> $TEST_LOG 2>&1 || true
# unshare -m ninja test >> $TEST_LOG 2>&1 || true
systemd-machine-id-setup
systemctl preset-all
rm -rf *
LANG=en_US.UTF-8                   \
meson setup --prefix=/usr          \
            --buildtype=release    \
            --cross-file=lib32     \
            -D default-dnssec=no   \
            -D firstboot=false     \
            -D install-tests=false \
            -D ldconfig=false      \
            -D sysusers=false      \
            -D rpmmacrosdir=no     \
            -D homed=disabled      \
            -D userdb=false        \
            -D man=disabled        \
            -D mode=release        \
            ..
LANG=en_US.UTF-8 ninja
LANG=en_US.UTF-8 DESTDIR=$PWD/DESTDIR ninja install
cp -av DESTDIR/usr/lib32/libsystemd.so* /usr/lib32/
cp -av DESTDIR/usr/lib32/libudev.so* /usr/lib32/
cp -v  DESTDIR/usr/lib32/pkgconfig/* /usr/lib32/pkgconfig/
rm -rf DESTDIR
echo -e "\n\nTotalseconds: $SECONDS\n"

# End of LFS book script

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"
cd $SRC_DIR
rm -rf $PKGDIR
if [ -d "${PKGDIR%-*}-build" ]; then  rm -rf ${PKGDIR%-*}-build; fi
exit
