#!/bin/bash
set +h
set -e



PREV_SEC=${SECONDS}
      
ROOT=/

SCRIPT_ROOT=jhalfs

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"

export MAKEFLAGS="-j4"
SECONDS=${PREV_SEC}

# Start of LFS book script
rm -rf /tmp/{*,.*}
find /usr/lib{,32,exec} -name \*.la -delete
find /usr -depth -name x86_64-lfs-linux-gnu\* | xargs rm -rf
userdel -r tester
echo -e "\n\nTotalseconds: $SECONDS\n"

# End of LFS book script

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"
exit
