#!/bin/bash

# This block must be edited to suit your needs.
cat > /etc/fstab << "EOF"
# Begin /etc/fstab

# file system  mount-point  type     options             dump  fsck
#                                                              order

/dev/**EDITME<xxx>EDITME**     /            **EDITME<fff>EDITME**    defaults            1     1
/dev/**EDITME<yyy>EDITME**     swap         swap     pri=1               0     0

# End /etc/fstab
EOF
# End of editable block.

hdparm -I /dev/sda | grep NCQ

