#!/bin/bash

bash /usr/lib/udev/init-net-rules.sh

cat /etc/udev/rules.d/70-persistent-net.rules

sed -e '/^AlternativeNamesPolicy/s/=.*$/=/'  \
       /usr/lib/udev/network/99-default.link \
     > /etc/udev/network/99-default.link

udevadm test /sys/block/hdd

# This block must be edited to suit your needs.
sed -e 's/"write_cd_rules"/"write_cd_rules **EDITMEmodeEDITME**"/' \
    -i /etc/udev/rules.d/83-cdrom-symlinks.rules
# End of editable block.

udevadm info -a -p /sys/class/video4linux/video0

cat > /etc/udev/rules.d/83-duplicate_devs.rules << "EOF"

# Persistent symlinks for webcam and tuner
KERNEL=="video*", ATTRS{idProduct}=="1910", ATTRS{idVendor}=="0d81", SYMLINK+="webcam"
KERNEL=="video*", ATTRS{device}=="0x036f",  ATTRS{vendor}=="0x109e", SYMLINK+="tvtuner"

EOF

