#!/bin/bash
# https://www.linuxfromscratch.org/blfs/view/systemd/postlfs/make-ca.html
# curl -s https://curl.se/docs/caextract.html| awk '/\/ca\/cacert-.*.pem/{print$3}'|head -1|sed 's/^.*cacert-\|.pem.*$\|-//g'

PKG="ca-certificates"
PKG_VERSION="20230530"
PKG_FILE="make-ca-1.12.tar.xz"
URL="https://github.com/lfs-book/make-ca/releases/download/v1.12/${PKG_FILE}"
MD5="67e0b911e73a859fc326171c5153d455"

for i in PATCH{1..10}; do
	unset $i
done

( cat << "xEOFx"
install -vdm755 /etc/ssl/local
/usr/sbin/make-ca -g

mkdir -pv /etc/profile.d
cat > /etc/profile.d/pythoncerts.sh << "EOF"
# Begin /etc/profile.d/pythoncerts.sh

export _PIP_STANDALONE_CERT=/etc/pki/tls/certs/ca-bundle.crt

# End /etc/profile.d/pythoncerts.sh
EOF
xEOFx
) > tmp
