#!/bin/bash
# https://packages.debian.org/source/sid/dpkg

PKG="dpkg"
PKG_VERSION="$(curl -sL https://packages.debian.org/source/sid/dpkg|awk '/.tar.xz/{print$2}'|sed 's/.*dpkg_\|.tar.*//g')"
PKG_FILE="${PKG}_${PKG_VERSION}.tar.xz"
URL="https://deb.debian.org/debian/pool/main/d/dpkg/${PKG_FILE}"
MD5="$(curl -sL https://packages.debian.org/source/sid/dpkg| grep -A2 .tar.xz|tail -1|sed 's/<.*">\|<\/.*//g')"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx

echo "$PKG_VERSION" > .dist-version
./autogen

./configure --prefix=/usr \
--docdir=/usr/share/doc/$PKG-${PKG_VERSION} \
--sysconfdir=/etc \
--localstatedir=/var \
--disable-start-stop-daemon

make
make install

install -vd /var/dpkg/updates
touch /var/lib/dpkg/{status,available}
ln -s less /usr/bin/pager

install -Dm644 /dev/stdin /etc/dpkg/origins/debian <<"EOF"
Vendor: Debian
Vendor-URL: https://www.debian.org/
EOF
ln -svf debian /etc/dpkg/origins/default
xEOFx
) > tmp
