#!/bin/bash
# https://linuxfromscratch.org/blfs/view/systemd/general/libgcrypt.html

PKG="libgcrypt"
PKG_VERSION="1.10.2"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.bz2"
URL="https://www.gnupg.org/ftp/gcrypt/libgcrypt/${PKG_FILE}"
MD5="663abb395452750522d6797967e2f442"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx
		./configure --prefix=/usr \
		--disable-static

make
make install
xEOFx
) > tmp
