#!/bin/bash
# https://www.linuxfromscratch.org/blfs/view/systemd/general/git.html

PKG="git"
PKG_VERSION="2.42.0"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.xz"
URL="https://www.kernel.org/pub/software/scm/git/${PKG_FILE}"
MD5="e61c187f6863d5e977e60cdedf213ec0"

for i in PATCH{1..10}; do
	unset $i
done

( cat << "xEOFx"
./configure --prefix=/usr \
		--with-gitconfig=/etc/gitconfig \
		--with-libpcre2 \
		--with-python=python3
make
perllibDIR="$(/usr/bin/perl -MConfig -wle 'print $Config{installsitelib}')"
make perllibdir=${perllibDIR} install
xEOFx
) > tmp
