#!/bin/bash
# https://linuxfromscratch.org/blfs/view/systemd/postlfs/gpgme.html

PKG="gpgme"
PKG_VERSION="1.21.0"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.bz2"
URL="https://www.gnupg.org/ftp/gcrypt/gpgme/${PKG_FILE}"
MD5="3a83288e753a7da53a5626d29e4416fd"

for i in PATCH{1..10}; do
	unset $i
done

( cat << "xEOFx"
./configure --prefix=/usr \
		--disable-static \
		--disable-gpg-test
make
make install
xEOFx
) > tmp
