#!/bin/bash
# https://gitlab.archlinux.org/archlinux/packaging/packages/pacman

PKG="pacman"
PKG_VERSION="6.0.2"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.xz"
URL="https://sources.archlinux.org/other/pacman/${PKG_FILE}"
MD5="f2c7e82cc5483a2c90f228a0393f5526"

for i in PATCH{1..10}; do
	unset $i
done

gitlab='https://gitlab.archlinux.org/pacman/pacman/-/commit'
PATCH1="${gitlab}/efd0c24c07b86be014a4edb5a8ece021b87e3900.patch"
PATCH2="${gitlab}/86981383a2f4380bda26311831be94cdc743649b.patch"
PATCH3="${gitlab}/478af273dfe24ded197ec54ae977ddc3719d74a0.patch"
PATCH4="${gitlab}/de11824527ec4e2561e161ac40a5714ec943543c.patch"

( cat << xEOFx
patch -Np1 -i ../${PATCH1##*/}
patch -Np1 -i ../${PATCH2##*/}
patch -Np1 -i ../${PATCH3##*/}
patch -Np1 -i ../${PATCH4##*/}

cat <<"EOF">> scripts/po/zh_CN.po

msgid "Splitting %s files into separate packages..."
msgstr "正在将 %s 文件拆分为单独的包..."

msgid "Removing man pages for the specified language..."
msgstr "正在删除指定语言的手册页..."

msgid "Removing the message translation file for the specified language..."
msgstr "正在删除指定语言的消息翻译文件..."

msgid "Finding %s files..."
msgstr "正在查找 %s 文件..."

msgid "Adding dependencies by dynamic linked library..."
msgstr "正在通过动态链接库添加依赖..."
EOF


mkdir -v pacman-build
cd pacman-build

meson setup --prefix=/usr \
		--buildtype=release \
		-Ddoc=disabled \
		-Ddoxygen=disabled \
		-Dscriptlet-shell=/usr/bin/bash \
		-Dldconfig=/usr/sbin/ldconfig ..
ninja
ninja install
xEOFx
) > tmp
