#!/bin/bash
# https://linuxfromscratch.org/blfs/view/systemd/general/libarchive.html

PKG="libarchive"
PKG_VERSION="3.6.2"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.xz"
URL="https://github.com/libarchive/libarchive/releases/download/v$PKG_VERSION/${PKG_FILE}"
MD5="72cbb3c085624c825f627bfc8f52ce53"

for i in PATCH{1..10}; do
	unset $i
done

( cat << "xEOFx"
./configure --prefix=/usr \
		--disable-static
make
make install
sed -i "s/iconv //" /usr/lib/pkgconfig/libarchive.pc
xEOFx
) > tmp
