#!/bin/bash
# https://www.linuxfromscratch.org/blfs/view/systemd/general/pcre2.html

PKG="pcre2"
PKG_VERSION="10.44"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.bz2"
URL="https://github.com/PCRE2Project/pcre2/releases/download/${PKG}-${PKG_VERSION}/${PKG_FILE}"
MD5="9d1fe11e2e919c7b395e3e8f0a5c3eec"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx
./configure --prefix=/usr \
		--disable-static \
		--docdir=/usr/share/doc/${PKG}-${PKG_VERSION} \
		--enable-unicode \
		\$([[ \$(gcc -dumpmachine) = *-gnux32 ]] || echo --enable-jit) \
		--enable-pcre2-16 \
		--enable-pcre2-32 \
		--enable-pcre2grep-libz \
		--enable-pcre2grep-libbz2 \
		--enable-pcre2test-libreadline

make
make install
xEOFx
) > tmp
