#!/bin/bash
# https://www.linuxfromscratch.org/blfs/view/systemd/postlfs/sudo.html

PKG="sudo"
PKG_VERSION="1.9.15p2"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.gz"
URL="https://www.sudo.ws/dist/${PKG_FILE}"
MD5="ef31b7ef72b386618990cfef94042541"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx
./configure --prefix=/usr \
		--libexecdir=/usr/lib \
		--with-secure-path \
		--with-all-insults \
		--with-env-editor \
		--without-pam \
		--docdir=/usr/share/doc/$PKG-${PKG_VERSION} \
		--with-passprompt=" 🔐 %p : "

make
make install
ln -sfv libsudo_util.so.0.0.0 /usr/lib/sudo/libsudo_util.so.0

sed -e '/root ALL=(ALL:ALL) ALL$/a\\nDefaults secure_path="\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:"\nDefaults timestamp_timeout=30' \
		-e '/^# %wheel ALL=(ALL:ALL) ALL$/s/#//' -i /etc/sudoers

xEOFx
) > tmp
