#!/bin/bash
# https://linuxfromscratch.org/blfs/view/systemd/general/libksba.html

PKG="libksba"
PKG_VERSION="1.6.7"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.bz2"
URL="https://www.gnupg.org/ftp/gcrypt/$PKG/${PKG_FILE}"
MD5="7e736de467b67c7ea88de746c31ea12f"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx
	./configure --prefix=/usr

make
make install
xEOFx
) > tmp
