#!/bin/bash

# This block must be edited to suit your needs.
mkdir -pv $LFS
mount -v -t ext4 /dev/**EDITME<xxx>EDITME** $LFS
# End of editable block.

# This block must be edited to suit your needs.
mkdir -pv $LFS
mount -v -t ext4 /dev/**EDITME<xxx>EDITME** $LFS
mkdir -v $LFS/home
mount -v -t ext4 /dev/**EDITME<yyy>EDITME** $LFS/home
# End of editable block.

# This block must be edited to suit your needs.
/sbin/swapon -v /dev/**EDITME<zzz>EDITME**
# End of editable block.

