#!/bin/bash
# https://www.linuxfromscratch.org/blfs/view/systemd/general/pcre2.html

PKG="pcre2"
PKG_VERSION="10.42"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.bz2"
URL="https://github.com/PCRE2Project/pcre2/releases/download/${PKG}-${PKG_VERSION}/${PKG_FILE}"
MD5="a8e9ab2935d428a4807461f183034abe"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx
./configure --prefix=/usr \
		--disable-static \
		--docdir=/usr/share/doc/${PKG}-${PKG_VERSION} \
		--enable-unicode \
		--enable-jit \
		--enable-pcre2-16 \
		--enable-pcre2-32 \
		--enable-pcre2grep-libz \
		--enable-pcre2grep-libbz2 \
		--enable-pcre2test-libreadline

make
make install
xEOFx
) > tmp
