#!/bin/bash
# https://linuxfromscratch.org/blfs/view/systemd/general/libuv.html

PKG="libuv"
PKG_VERSION="1.48.0"
PKG_FILE="${PKG}-v${PKG_VERSION}.tar.gz"
URL="https://dist.libuv.org/dist/v${PKG_VERSION}/${PKG_FILE}"
MD5="a808517c32ebd07c561bf21a4e30aeab"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx
sh autogen.sh
./configure --prefix=/usr --disable-static

make
make install
xEOFx
) > tmp
