#!/bin/bash
# https://gitlab.archlinux.org/archlinux/packaging/packages/pacman

PKG="pacman"
PKG_VERSION="6.1.0"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.xz"
URL="https://gitlab.archlinux.org/pacman/pacman/-/releases/v${PKG_VERSION}/downloads/${PKG_FILE}"
MD5="09ec3d2827b4b37554956035646815d9"

for i in PATCH{1..10}; do
	unset $i
done

gitlab='https://gitlab.archlinux.org/pacman/pacman/-/commit'
PATCH1="${gitlab}/6bb95c8856437513ee0ab19226bc090d6fd0fb06.patch"
PATCH2="${gitlab}/95f148c2222db608a0d72d5c5577d0c71e7fa199.patch"
PATCH3="${gitlab}/5e0496260b7d3f9c9fcf2b1c4899e4dbcc20ff03.patch"
PATCH4="${gitlab}/0571ee82bff0edbd5ffac2228d4e6ac510b9008e.patch"
PATCH5="${gitlab}/111eed0251238a9d3f90e76d62f2ac01aeccce48.patch"
PATCH6="${gitlab}/bae9594ac1806ce30f2af1de27c49bb101a00d44.patch"

( cat << xEOFx

wget -nv -O revertme-makepkg-remove-libdepends-and-libprovides.patch \
	"${gitlab}/354a300cd26bb1c7e6551473596be5ecced921de.patch"
patch -RNp1 -i revertme-makepkg-remove-libdepends-and-libprovides.patch

patch -Np1 -i ../${PATCH1##*/}
patch -Np1 -i ../${PATCH2##*/}
patch -Np1 -i ../${PATCH3##*/}
patch -Np1 -i ../${PATCH4##*/}
patch -Np1 -i ../${PATCH5##*/}
patch -Np1 -i ../${PATCH6##*/}


cat <<"EOF">> scripts/po/zh_CN.po

msgid "Splitting %s files into separate packages..."
msgstr "正在将 %s 文件拆分为单独的包..."

msgid "Splitting static library files into separate packages..."
msgstr "正在将静态库文件拆分为单独的包..."

msgid "Removing unwanted man pages..."
msgstr "正在删除不想要的手册页..."

msgid "Removing unwanted message translation files..."
msgstr "正在删除不想要的翻译文件..."

msgid "Finding %s files..."
msgstr "正在查找 %s 文件..."

msgid "Adding dependencies by dynamic linked library..."
msgstr "正在通过动态链接库添加依赖..."
EOF


mkdir -v pacman-build
cd pacman-build

meson setup --prefix=/usr \
		--buildtype=release \
		--libdir=/usr/lib \
		-Ddoc=disabled \
		-Ddoxygen=disabled \
		-Dscriptlet-shell=/usr/bin/bash \
		-Dldconfig=/usr/sbin/ldconfig ..
ninja
ninja install
xEOFx
) > tmp
