#!/bin/bash
# https://linuxfromscratch.org/blfs/view/systemd/general/libgcrypt.html

PKG="libgcrypt"
PKG_VERSION="1.11.0"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.bz2"
URL="https://www.gnupg.org/ftp/gcrypt/libgcrypt/${PKG_FILE}"
MD5="321c4975cfd6a496f0530b65a673f9a4"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx
		./configure --prefix=/usr \
		--disable-static

make
make install
xEOFx
) > tmp
