#!/bin/bash
# https://gitlab.archlinux.org/archlinux/packaging/packages/fakeroot
# https://packages.debian.org/source/sid/fakeroot

D_DATE=20240716T023930Z
D_URL=https://snapshot.debian.org/archive/debian/$D_DATE

PKG="fakeroot"
PKG_VERSION="1.35"
PKG_FILE="${PKG}_${PKG_VERSION}.orig.tar.gz"
URL="https://deb.debian.org/debian/pool/main/${PKG::1}/$PKG/${PKG_FILE}"
URL="$D_URL/pool/main/${PKG::1}/$PKG/${PKG_FILE}"
MD5="0d692daf0f145289b94530bbb6aa6b2c"

for i in PATCH{1..10}; do
	unset $i
done

( cat << "xEOFx"
./configure --prefix=/usr \
		--disable-static
make
make install
xEOFx
) > tmp
