#!/bin/bash
# https://www.linuxfromscratch.org/blfs/view/systemd/postlfs/make-ca.html
# curl -s https://curl.se/docs/caextract.html| awk '/\/ca\/cacert-.*.pem/{print$3}'|head -1|sed 's/^.*cacert-\|.pem.*$\|-//g'

PKG="ca-certificates"
PKG_VERSION="20240702"
PKG_FILE="make-ca-1.13.tar.xz"
URL="https://github.com/lfs-book/make-ca/releases/download/v1.13/${PKG_FILE}"
MD5="04bd86fe2eb299788439c3466782ce45"

for i in PATCH{1..10}; do
	unset $i
done

( cat << "xEOFx"
install -vdm755 /etc/ssl/local
/usr/sbin/make-ca -g
ln -sfv ../tls/certs/ca-bundle.crt /etc/ssl/cert.pem

mkdir -pv /etc/profile.d
cat > /etc/profile.d/pythoncerts.sh << "EOF"
# Begin /etc/profile.d/pythoncerts.sh

export _PIP_STANDALONE_CERT=/etc/tls/certs/ca-bundle.crt

# End /etc/profile.d/pythoncerts.sh
EOF
xEOFx
) > tmp
