#!/bin/bash
# https://linuxfromscratch.org/blfs/view/systemd/general/libksba.html

PKG="libksba"
PKG_VERSION="1.6.4"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.bz2"
URL="https://www.gnupg.org/ftp/gcrypt/$PKG/${PKG_FILE}"
MD5="17a0b93de57cd91c7e3264b107723092"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx
		./configure --prefix=/usr \
		--disable-static

make
make install
xEOFx
) > tmp
