#!/bin/bash
# https://linuxfromscratch.org/blfs/view/systemd/general/libassuan.html

PKG="libassuan"
PKG_VERSION="3.0.1"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.bz2"
URL="https://www.gnupg.org/ftp/gcrypt/libassuan/${PKG_FILE}"
MD5="6f0d239302ae3b8d4aefcb499b137530"

for i in PATCH{1..10}; do
	unset $i
done

( cat << "xEOFx"
./configure --prefix=/usr \
		--disable-static
make
make install
xEOFx
) > tmp
