#!/bin/bash
# https://linuxfromscratch.org/blfs/view/systemd/general/npth.html

PKG="npth"
PKG_VERSION="1.7"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.bz2"
URL="https://www.gnupg.org/ftp/gcrypt/$PKG/${PKG_FILE}"
MD5="286274d0106ec408efebe4a399975b11"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx
	./configure --prefix=/usr

make
make install
xEOFx
) > tmp
