#!/bin/bash
# https://www.linuxfromscratch.org/blfs/view/systemd/postlfs/linux-pam.html

PKG="linux-pam"
PKG_VERSION="1.6.0"
PKG_FILE="Linux-PAM-${PKG_VERSION}.tar.xz"
URL="https://github.com/linux-pam/linux-pam/releases/download/v${PKG_VERSION}/${PKG_FILE}"
MD5="41a10af5fc35a7be472ae9864338e64a"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx
./configure --prefix=/usr \
		--sbindir=/usr/sbin \
		--sysconfdir=/etc \
		--libdir=/usr/lib \
		--enable-securedir=/usr/lib/security \
		--docdir=/usr/share/doc/$PKG-${PKG_VERSION}

make
make install
chmod -v 4755 /usr/sbin/unix_chkpwd
xEOFx
) > tmp
