#!/bin/bash
# https://linuxfromscratch.org/blfs/view/systemd/general/npth.html

PKG="npth"
PKG_VERSION="1.6"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.bz2"
URL="https://www.gnupg.org/ftp/gcrypt/$PKG/${PKG_FILE}"
MD5="375d1a15ad969f32d25f1a7630929854"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx
		./configure --prefix=/usr \
		--disable-static

make
make install
xEOFx
) > tmp
