#!/bin/bash
# https://linuxfromscratch.org/blfs/view/systemd/basicnet/curl.html

PKG="curl"
PKG_VERSION="8.1.2"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.xz"
URL="https://curl.se/download/${PKG_FILE}"
MD5="1f7f6678b1342ad78f30e1dedd015fe2"

for i in PATCH{1..10}; do
	unset $i
done

( cat << "xEOFx"
./configure --prefix=/usr \
            --disable-static \
            --with-openssl \
            --enable-threaded-resolver \
            --with-ca-path=/etc/ssl/certs
make
make install
xEOFx
) > tmp
