#!/bin/bash
# https://linuxfromscratch.org/blfs/view/systemd/postlfs/nettle.html

PKG="nettle"
PKG_VERSION="3.9.1"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.gz"
URL="https://ftp.gnu.org/gnu/${PKG}/${PKG_FILE}"
MD5="29fcd2dec6bf5b48e5e3ffb3cbc4779e"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx
	./configure --prefix=/usr \
		--disable-static \
		--libdir=/usr/lib

make
make install
xEOFx
) > tmp
