#!/bin/bash
# https://packages.debian.org/source/sid/dpkg

PKG="dpkg"
PKG_VERSION="1.21.22"
PKG_FILE="${PKG}_${PKG_VERSION}.tar.xz"
URL="https://deb.debian.org/debian/pool/main/d/dpkg/${PKG_FILE}"
MD5="0577cef4dafe3e7759ef0b53a4783874"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx

echo "$PKG_VERSION" > .dist-version
./autogen

./configure --prefix=/usr \
--sysconfdir=/etc \
--localstatedir=/var \
--disable-start-stop-daemon

make
make install

install -vd /var/dpkg/updates
touch /var/lib/dpkg/{status,available}
ln -s less /usr/bin/pager

install -Dm644 /dev/stdin /etc/dpkg/origins/debian <<"EOF"
Vendor: Debian
Vendor-URL: https://www.debian.org/
EOF
ln -svf debian /etc/dpkg/origins/default
xEOFx
) > tmp
