#!/bin/bash
# https://packages.debian.org/source/sid/dpkg

PKG="dpkg"
PKG_VERSION="1.22.1"
PKG_FILE="dpkg_1.22.1.tar.xz"
URL="https://deb.debian.org/debian/pool/main/d/dpkg/dpkg_1.22.1.tar.xz"
MD5="d265eeaee92f81580ac6b34c07d41eb5"

for i in PATCH{1..10}; do
	unset $i
done

( cat << xEOFx

echo "$PKG_VERSION" > .dist-version
./autogen

./configure --prefix=/usr \
--docdir=/usr/share/doc/$PKG-${PKG_VERSION} \
--sysconfdir=/etc \
--localstatedir=/var \
--disable-start-stop-daemon

make
make install

install -vd /var/dpkg/updates
touch /var/lib/dpkg/{status,available}
ln -s less /usr/bin/pager

install -Dm644 /dev/stdin /etc/dpkg/origins/debian <<"EOF"
Vendor: Debian
Vendor-URL: https://www.debian.org/
EOF
ln -svf debian /etc/dpkg/origins/default
xEOFx
) > tmp
