#!/bin/bash
set +h
set -e



PREV_SEC=${SECONDS}
      
ROOT=$LFS/

SCRIPT_ROOT=jhalfs

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"

export MAKEFLAGS="-j4"
SECONDS=${PREV_SEC}

# Start of LFS book script
chown --from lfs -R root:root $LFS/{usr,lib64,var,etc,tools}
echo -e "\n\nTotalseconds: $SECONDS\n"

# End of LFS book script

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"
exit
