#!/bin/bash
# https://linuxfromscratch.org/blfs/view/systemd/general/lua.html

PKG="lua"
PKG_VERSION="5.4.6"
PKG_FILE="${PKG}-${PKG_VERSION}.tar.gz"
URL="https://www.lua.org/ftp/${PKG_FILE}"
MD5="25a429319dff20dfbfb9956c2b5be911"

for i in PATCH{1..10}; do
	unset $i
done

PATCH1="https://www.linuxfromscratch.org/patches/blfs/svn/lua-${PKG_VERSION}-shared_library-1.patch"

( cat << xEOFx
cat > lua.pc << "EOF"
V=5.4
R=5.4.6

prefix=/usr
INSTALL_BIN=\${prefix}/bin
INSTALL_INC=\${prefix}/include
INSTALL_LIB=\${prefix}/lib
INSTALL_MAN=\${prefix}/share/man/man1
INSTALL_LMOD=\${prefix}/share/lua/\${V}
INSTALL_CMOD=\${prefix}/lib/lua/\${V}
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: Lua
Description: An Extensible Extension Language
Version: \${R}
Requires:
Libs: -L\${libdir} -llua -lm -ldl
Cflags: -I\${includedir}
EOF


patch -Np1 -i ../lua-${PKG_VERSION}-shared_library-1.patch
make linux
make INSTALL_TOP=/usr install \
	INSTALL_DATA="cp -d" \
	INSTALL_MAN=/usr/share/man/man1 \
	TO_LIB="liblua.so liblua.so.5.4 liblua.so.5.4.6"

install -Dvm644 lua.pc /usr/lib/pkgconfig/lua.pc
xEOFx
) > tmp
