#!/bin/bash
set +h
set -e



PREV_SEC=${SECONDS}
      
ROOT=/

SCRIPT_ROOT=jhalfs

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"

export MAKEFLAGS="-j4"
SECONDS=${PREV_SEC}

# Start of LFS book script
cat > /etc/systemd/network/10-eth-static.network << "EOF"
[Match]
Name=eth0

[Network]
Address=10.0.2.9/24
Gateway=10.0.2.2
DNS=1.1.1.1
DNS=8.8.8.8
Domains=local
EOF
echo "Linux®FromScratch" > /etc/hostname
cat > /etc/hosts << "EOF"
# Begin /etc/hosts

10.0.2.9 Linux®FromScratch.local 
::1       ip6-localhost ip6-loopback
ff02::1   ip6-allnodes
ff02::2   ip6-allrouters

# End /etc/hosts
EOF
echo -e "\n\nTotalseconds: $SECONDS\n"

# End of LFS book script

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"
exit
