#!/bin/bash

bld_dir="$(grep '^BUILDDIR=' alfs/configuration|sed -e 's/^BUILDDIR=//' -e 's/"//g')"

_cleanup_dir() {
		rm -rf "${bld_dir}/usr/"{,local/}lib/python*/{test,ctypes/test,distutils/tests,idlelib/idle_test,lib2to3/tests,sqlite3/test,tkinter/test,unittest/test}
		rm -rf "${bld_dir}/tools"* "${bld_dir}/usr"{,local}/share/info

		find "${bld_dir}/usr" -type f -name '*.la' -delete
		for i in "${bld_dir}/jhalfs/installed-files"/*; do
			local change="$(grep '\.la\s' $i)"
			[ -z "$change" ] || sed -i '/.la\s/d' "$i"
		done

		find "${bld_dir}/var/cache" ! -type d -delete
		find "${bld_dir}/etc/ld.so.cache" -delete

		if [ -d "${bld_dir}/var/lib/systemd" ]; then
			find "${bld_dir}/var/lib/systemd" ! -type d -delete
		fi
}

_strip_symbol() {
		local DEST="${bld_dir}/usr"
		local STRIP_BINARIES="--strip-all"
		local STRIP_SHARED="--strip-unneeded"
		local STRIP_STATIC="--strip-debug"

		find "${DEST}" -type f -name '*.dbg' -delete

		strip_file() {
			local binary=$1; shift
			local tempfile=$(mktemp "$binary.XXXXXX")
			if strip "$@" "$binary" -o "$tempfile"; then
				cat "$tempfile" > "$binary"
			fi
			rm -f "$tempfile"
		}

		local binary strip_flags
		find "${DEST}" -type f -perm -u+w -print0 2>/dev/null | while IFS= read -rd '' binary ; do
			case "$(LC_ALL=C readelf -h "$binary" 2>/dev/null)" in
				*Type:*'DYN (Shared object file)'*) # Libraries (.so) or Relocatable binaries
					strip_flags="$STRIP_SHARED";;
				*Type:*'DYN (Position-Independent Executable file)'*) # Relocatable binaries
					strip_flags="$STRIP_SHARED";;
				*Type:*'EXEC (Executable file)'*) # Binaries
					strip_flags="$STRIP_BINARIES";;
				*Type:*'REL (Relocatable file)'*) # Libraries (.a) or objects
					if ar t "$binary" &>/dev/null; then # Libraries (.a)
						strip_flags="$STRIP_STATIC"
					elif [[ $binary = *'.ko' || $binary = *'.o' ]]; then # Kernel module or object file
						strip_flags="$STRIP_SHARED"
					else
						continue
					fi
					;;
				*)
					continue ;;
			esac
			pushd /tmp >/dev/null
			strip_file "$binary" ${strip_flags}
			popd >/dev/null
		done
}

_remove_staticlib() {
		printf "Removing static library files..."
		local l
		while IFS= read -rd '' l; do
			if [[ -f "${l%.a}.so" || -h "${l%.a}.so" ]]; then
				rm "$l"
			fi
		done < <(find "${bld_dir}/usr" ! -type d -name "*.a" -print0)
		printf 'done.\n'
}

_system_conf() {
		install -Dm644 /dev/stdin "${bld_dir}/etc/profile" <<"EFO"
# System wide environment variables and startup programs.

# System wide aliases and functions should go in /etc/bashrc.  Personal
# environment variables and startup programs should go into
# ~/.bash_profile.  Personal aliases and functions should go into
# ~/.bashrc.

# Functions to help us manage paths.  Second argument is the name of the
# path variable to be modified (default: PATH)

# Set the initial path
export PATH=/usr/bin:/usr/sbin:/usr/local/bin


# Setup some environment variables.
export HISTSIZE=10000
export HISTIGNORE="&:[bf]g:exit"

# Set some defaults for graphical systems
export XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/share/}
export XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:-/etc/xdg/}
export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/tmp/xdg-$USER}
export XDG_CONFIG_HOME=${HOME}/.config

if [ -e /etc/hostname ]; then
	HOST="$(cat /etc/hostname)"
	[ -n "$HOST" ] || HOST='\H'
else
	HOST='\H'
fi

# Setup a red prompt for root and a green one for users.
NORMAL="\[\e[0m\]"
RED="\[\e[1;31m\]"
GREEN="\[\e[1;32m\]"
if [[ $EUID == 0 ]] ; then
	PS1="$RED\u@$HOST $NORMAL\w$RED \A # $NORMAL"
else
	PS1="$GREEN\u@$HOST $NORMAL\w$GREEN \A \$ $NORMAL"
fi

for script in /etc/profile.d/*.sh ; do
        if [ -r $script ] ; then
                . $script
        fi
done

unset script RED GREEN NORMAL HOST


alias ls='ls --color=auto'
alias ll='ls -l --color=auto'
alias la='ls -A --color=auto'
alias lla='ls -la --color=auto'
alias llh='ls -lh --color=auto'
alias llah='ls -lah --color=auto'

alias proxyon='export http_proxy=127.0.0.1:7890 https_proxy=127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7891 && curl -I google.com'
alias proxyoff='unset http_proxy https_proxy all_proxy'
alias df='df -Th'
alias free='free -h'
alias tree='tree -C'

export EDITOR=/usr/bin/nano
export VISUAL=/usr/bin/nano
export NINJA_STATUS="[%r %f/%t %es] "
EFO

		echo 'if [ -e /etc/profile ]; then source /etc/profile; fi' >> "${bld_dir}/root/.bashrc"
		[ -d "${bld_dir}/etc/skel/" ] || mkdir -p "${bld_dir}/etc/skel"
		echo 'if [ -e /etc/profile ]; then source /etc/profile; fi' >> "${bld_dir}/etc/skel/.bashrc"
		echo "Generating locales..."
		[ ! -e "${bld_dir}/usr/lib/locale/locale-archive" ] || rm "${bld_dir}/usr/lib/locale/locale-archive"
		localedef --prefix="${bld_dir}" -i POSIX -f UTF-8 C.UTF-8 2>/dev/null || true
		localedef --prefix="${bld_dir}" -i en_GB -f UTF-8 en_GB.UTF-8
		localedef --prefix="${bld_dir}" -i en_US -f UTF-8 en_US.UTF-8
		localedef --prefix="${bld_dir}" -i zh_CN -f UTF-8 zh_CN.UTF-8
}

_pacman_conf(){
		git clone --depth=1 "https://github.com/windsey/script" packmgr
		make DESTDIR="${bld_dir}" install -C packmgr/makepkg
		install -Dm644 /dev/stdin "${bld_dir}/etc/makepkg.conf" <<"EF"
DLAGENTS=('file::/usr/bin/curl -qgC - -o %o %u'
          'ftp::/usr/bin/curl -qgfC - --ftp-pasv --retry 3 --retry-delay 3 -o %o %u'
          'http::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 3 -o %o %u'
          'https::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 3 -o %o %u'
          'rsync::/usr/bin/rsync --no-motd -z %u %o'
          'scp::/usr/bin/scp -C %u %o')
VCSCLIENTS=('bzr::bzr'
            'fossil::fossil'
            'git::git'
            'hg::mercurial'
            'svn::subversion')
CARCH="x86_64"
CHOST="x86_64-pc-linux-gnu"
CFLAGS="-march=haswell -O2 -pipe -fno-plt -fPIC -DNDEBUG -w"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS="-flto=auto"
RUSTFLAGS="-C opt-level=2"
CPPFLAGS="-O2 -pipe -fPIC -DNDEBUG -w"
MAKEFLAGS="-j$(nproc)"
BUILDENV=(!distcc color !ccache check !sign)
BUILDDIR=/build/workdir
OPTIONS=(addep rman strip docs !html lfs !locale !libtool !staticlibs emptydirs zipman purge !debug lto)
. /etc/pacman.d/localedir
. /etc/pacman.d/rmandir
INTEGRITY_CHECK=(sha256)
STRIP_BINARIES="--strip-all"
STRIP_SHARED="--strip-unneeded"
STRIP_STATIC="--strip-debug"
MAN_DIRS=({usr{,/local}{,/share},opt/*}/{man,info})
DOC_DIRS=(usr/{,local/}{,share/}{doc,gtk-doc} opt/*/{doc,gtk-doc}) #usr/share/info)
PURGE_TARGETS=(usr/{,share}/info/dir .packlist *.pod) #usr/share/info/*)
PKGDEST=/build/packages
SRCDEST=/build/sources
PACKAGER="Github Action <build-bot@$(hostname)>"
COMPRESSGZ=(gzip -c -f -n)
COMPRESSBZ2=(bzip2 -c -f)
COMPRESSXZ=(xz -c -z --threads=0 -)
COMPRESSZST=(zstd -c -z -q --threads=0 -)
COMPRESSLRZ=(lrzip -q)
COMPRESSLZO=(lzop -q)
COMPRESSZ=(compress -c -f)
COMPRESSLZ4=(lz4 -q)
COMPRESSLZ=(lzip -c -f)
PKGEXT='.pkg.tar.xz'
SRCEXT='.src.tar.xz'
EF

		sed -e '/^#Color/s/#//' -e '/^#VerbosePkgLists/s/#//' -e 's/^CheckSpace/#&/' -i "${bld_dir}/etc/pacman.conf"
		install -dv "${bld_dir}/var/lib/pacman/local"
		echo "Updating alpm library database..."
		mountpoint -q "${bld_dir}/dev" || mount -v --bind /dev "${bld_dir}/dev"
		mountpoint -q "${bld_dir}/dev/pts" || mount -v --bind /dev/pts "${bld_dir}/dev/pts"
		mountpoint -q "${bld_dir}/proc" || mount -vt proc proc "${bld_dir}"/proc
		chroot "${bld_dir}" /usr/bin/env -i HOME=/root TERM="$TERM" PATH=/usr/bin:/usr/sbin /bin/bash -c pacman-db-upgrade
		mountpoint -q "${bld_dir}/proc" && umount -v "${bld_dir}/proc" || true
		mountpoint -q "${bld_dir}/dev/pts" && umount -lv "${bld_dir}/dev/pts" || true
		mountpoint -q "${bld_dir}/dev" && umount -lv "${bld_dir}/dev" || true
}

_zipman() {
		local MAN_DIRS=("${bld_dir}"/usr{,/local}/share/man)
		local file files inode link
		echo  "Compressing man pages..."
		while read -rd ' ' inode; do
			IFS= read -r file
			find "${MAN_DIRS[@]}" -type l -print0 2>/dev/null |
			while IFS= read -rd '' link ; do
				if [[ "${file}" -ef "${link}" ]] ; then
					rm -f "$link" "${link}.gz"
					if [[ ${file%/*} = "${link%/*}" ]]; then
						ln -s -- "${file##*/}.gz" "${link}.gz"
					else
						ln -s -- "/${file}.gz" "${link}.gz"
					fi
				fi
			done
			if [[ -z ${files[$inode]} ]]; then
				files[$inode]=$file
				gzip -9 -n -f "$file"
			else
				rm -f "$file"
				ln "${files[$inode]}.gz" "${file}.gz"
				chmod 644 "${file}.gz"
			fi
		done < <(find "${MAN_DIRS[@]}" -type f \! -name "*.gz" \! -name "*.bz2" \
			-exec stat -c '%i %n' '{}' + 2>/dev/null)
}

_docmd() {
		printf '::Removing Python test files and Tools directory...'
		_cleanup_dir
		printf 'done.\n'

		printf "::Remove all symbol and relocation information from binaries and libraries, in '${bld_dir}/usr'..."
		_strip_symbol
		printf 'done.\n'

		case "$1" in
			rm_static|no_static) _remove_staticlib ;;
		esac

		printf '::Seting Some System Configuration...'
		_system_conf
		 _pacman_conf
		#_zipman # need to waste a lot of time
		printf 'done.\n'
}

_docmd
