name: Build multilib i686
on:
  workflow_dispatch:
  schedule:
    - cron: '5 7 */30 * *'
    #- cron: '5 14,20 7 5 0' #Runs at 14:05 and 20:05, on day 7 of the month, and on Sunday, only in May. UTC (Two triggers: specific date, the day of the week)
    #- cron: '5 02,08 8 5 *' #Runs at 02:05 and 08:05, on day 8 of the month, only in May. UTC (One trigger: specific date)
    #- cron: '5 10 */7 * *' #Runs at 10:05, every 7 days. UTC

jobs:
  build-m32:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check
        run: |
          echo "Processor: $(cat /proc/cpuinfo|grep processor|wc -l)"
          cat /proc/cpuinfo|grep 'model name'|head -1
          cat /proc/meminfo|head; echo ' '
          sudo ln -sf bash /bin/sh
          bash -e script/version-check

      - name: Build
        run: |
          bash -e script/build m32
          echo ' '; df -Th; echo ' '; free -h

      - name: Cleanup, Remove symbol and System Configuration
        run: |
          sudo bash -e script/cleanup || { cd alfs; bash -e ../script/build failed; }
          echo ' '; df -Th; echo ' '; free -h

      - name: Push To tags
        run: bash -e script/push release

      - name: Upload to Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          body: ${{ env.TAG_DES }}
          files: upload/*
          prerelease: false
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 3
          delete_tags: true
          delete_tag_pattern: .r
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debugging with SSH
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/$GITHUB_ACTOR/8210020cdb17776e9bbfa9048a0d9609/raw | bash
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          USER_SSH_KEY: ${{ secrets.USER_SSH_KEY }}
      - name: Don't kill instace
        if: ${{ failure() }}
        run: while true; do echo -e "$(date; df -Th)\n"; sleep 15m; done
